<?php
/**
 * Implements hook_menu_alter
 */
function ding_modal_menu_alter(&$items) {
  $modals = ding_modal_invoke_menu_hook();
  foreach($modals as $path => $modal_item){
    if(isset($items[$path])){
      $items[$path] = ding_modal_ajaxify_menu_item($items[$path], $modal_item);
    }
  }
}

/**
 * Alter a menu item to be ajax enabled.
 *
 * @param $menu_item
 * @param $modal_item
 */
function ding_modal_ajaxify_menu_item($menu_item, $modal_item){
  // ajax deliver
  $modal_item['delivery callback'] = 'ajax_deliver';
  // if form id is given: overwrite page callback
  if (isset($modal_item['form_id'])) {
    $modal_item['page callback'] = 'ding_modal_page_callback';
  }

  return $modal_item + $menu_item;
}

/**
 * Menu callback that returns the form in an AJAX callback.
 *
 * @return array
 */
function ding_modal_page_callback($form_id) {

  $form = call_user_func_array('drupal_get_form', func_get_args());

  // set ajax attributes on form
  _ding_modal_submit_attributes($form);

  $render = array(
    '#theme' => 'ding_modal_theme',
    '#title' => isset($form['#title']) ? $form['#title'] : drupal_get_title(),
    '#content' => $form,
  );

  $commands[] = ajax_command_invoke('#ding-modal', 'foundation', array('reveal', 'open'));
  $commands[] = ajax_command_html('#ding-modal', drupal_render($render));

  return array('#type' => 'ajax', '#commands' => $commands);
}


/**
 * Implements hook_page_build().
 * Add the search/replace data to javascript settings.
 * See: DingModal.rewritelinks in js/ding_modal.js
 */
function ding_modal_page_build(&$page) {
  drupal_add_js(array('ding_modal' => array('ding_modal_settings' => _ding_modal_js_settings())), 'setting');
  drupal_add_library('system', 'jquery.form');
  drupal_add_library('system', 'drupal.ajax');
}


/**
 * Implements hook_theme().
 */
function ding_modal_theme() {
  return array(
    'ding_modal_theme' => array(
      'template' => 'theme/ding-modal',
      'variables' => array(
        'title' => '',
        'content' => '',
      ),
    ),
  );
}

/**
 * Invoke hook_ding_modal_menus
 */
function ding_modal_invoke_menu_hook(){
  $modals = &drupal_static(__FUNCTION__);
  if (!isset($modals)) {
    $modals = module_invoke_all('ding_modal_menus');
  }
  return $modals;
}


/**
 * Helper function to populate menu items.
 *
 * Add #ajaxt attribute on submit buttons to ensure Drupal will
 * ajax-process the form and avoid a new pageload when the form is submitted.
 *
 * @return array
 */
function _ding_modal_submit_attributes(&$form) {
  foreach ($form as $key => $item) {
    if(is_object($item)){
      continue;
    }
    if (!empty($item['#type']) && $item['#type'] == "submit") {
      $form[$key]['#attributes']['class'][] = 'use-ajax-submit';
      if (empty($form[$key]['#ajax'])) {
        $form[$key]['#ajax'] = array(
          'callback' => 'ajax_form_callback',
          'wrapper' => 'ding-modal-content',
          'method' => 'replace',
          'effect' => 'fade',
          'speed' => 'slow',
        );
      }
    }
    if ($key[0] != "#") {
      // check form recursively
      _ding_modal_submit_attributes($form[$key]);
    }
  }
}



/**
 * Helper function to populate javascript settings.
 */
function _ding_modal_js_settings() {

  $ding_modal_settings = array();
  $items = ding_modal_invoke_menu_hook();

  foreach ($items as $path => $item) {
    $ding_modal_setting['id'] = $path;
    $ding_modal_setting['selectors'] = $item['selectors'];
    $ding_modal_settings[$path] = $ding_modal_setting;
  }

  return $ding_modal_settings;
}
